version: '1'

# Code coverage configuration
coverage:
  enable: all
  threshold:
    statements: 80
    branches: 75
    functions: 80
    lines: 80

# Code quality checks
checks:
  - id: complexity
    config:
      max_complexity: 10
  - id: duplication
    config:
      min_lines: 5
  - id: security
    enable: true
  - id: performance
    enable: true
  - id: maintainability
    enable: true

# Language-specific configurations
typescript:
  version: '5.8.3'
  strict: true

javascript:
  ecmaVersion: 2022

svelte:
  enable: true

# Plugins to use
plugins:
  - eslint
  - prettier
  - vitest
  - playwright
  - knip
  - size-limit

# Custom rules
rules:
  # Enforce Bun usage
  - id: no-npm-commands
    message: 'Use Bun instead of npm/yarn/pnpm'
    pattern: 'npm |yarn |pnpm '
    severity: error
    include:
      - '**/*.json'
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.sh'

  # Enforce consistent imports
  - id: consistent-imports
    message: 'Use consistent import patterns'
    severity: warning

# Ignore patterns
ignore:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/.svelte-kit/**'
  - '**/coverage/**'
  - '**/reports/**'
  - '**/*.min.js'
  - '**/*.min.css'

# Reporting
reports:
  format:
    - console
    - html
    - json
  output: './reports/qlty'

# Integrations
integrations:
  git_hooks:
    pre_commit: true
    pre_push: true
  ci:
    provider: github-actions
    fail_on_issues: true

# Performance budget
performance:
  bundle_size:
    warning: 150000 # 150KB
    error: 200000 # 200KB
  first_load:
    warning: 3000 # 3s
    error: 5000 # 5s
