# Netlify configuration for A Hacker's Brand Design System

[build]
  # Build command using Bun
  command = "bun install && bun run build"
  
  # Directory to deploy (SvelteKit outputs to 'build')
  publish = "build"
  
  # Node version for build environment (matches .nvmrc)
  environment = { NODE_VERSION = "20.10.0" }

[build.environment]
  # Use Bun in production builds
  NPM_FLAGS = "--version" # Prevents npm install
  # Enable Bun
  BUN_VERSION = "1.2.19"
  
[build.processing]
  skip = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # Cache static assets
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/"
  [headers.values]
    # Don't cache HTML
    Cache-Control = "no-cache"

[[headers]]
  for = "/docs/*"
  [headers.values]
    # Don't cache documentation pages
    Cache-Control = "no-cache"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}

# Redirect www to non-www
[[redirects]]
  from = "https://www.hackersbrand.design/*"
  to = "https://hackersbrand.design/:splat"
  status = 301
  force = true

# API proxy (if needed in future)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[functions]
  # Directory for serverless functions
  directory = "netlify/functions"
  
  # Node version for functions
  node_bundler = "esbuild"

# Build plugins
# Environment variables
[context.production.environment]
  VITE_ENV = "production"

[context.deploy-preview.environment]
  VITE_ENV = "preview"

[context.branch-deploy.environment]
  VITE_ENV = "development"

# Post processing
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  minify = true

[build.processing.images]
  compress = true

# Plugins
[[plugins]]
  # Lighthouse CI for performance monitoring
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    # Test specific pages
    audits.url = [
      "/",
      "/docs/getting-started",
      "/docs/components"
    ]
    
    # Performance thresholds
    thresholds.performance = 0.95
    thresholds.accessibility = 1.0
    thresholds.best-practices = 0.95
    thresholds.seo = 0.95

# Development settings
[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173
  
[context.production]
  environment = { VITE_ENV = "production" }
  
[context.deploy-preview]
  environment = { VITE_ENV = "preview" }
  
[context.branch-deploy]
  environment = { VITE_ENV = "development" }